### ISSUE TITLE
User can able inappropriate Additional Cost and Services from product edit page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#100]
**Woo Commerce Version** - 7.9.0
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.2
**Description** - User can able inappropriate Additional Cost and Services from product edit page

https://nimb.ws/az2jBi

**Comment by Sukirti-CEDCOSS** [comment]
woocommerce default functionality

**Comment by WP-Swings** [comment]
need to work

**Comment by navneet-cedcoss** [comment]
When a user adds any non-existent additional cost, they must manually input the amount from the backend to include the cost.
