### ISSUE TITLE
Availability option is not working in minutes 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#104]
**Woo Commerce Version** - 8.0.2
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.2
**Description** - Availability option is not working in minutes 

![Screenshot from 2023-08-24 15-21-23](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/f02aeab9-e5cd-4e29-a447-764b7a4eaac8)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
