### ISSUE TITLE
Design issue in calendar length

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#105]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 3.1.3
Description -
Make the calendar length equal to the input box
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/4e57fb50-372d-43b3-8a57-3175a65a9403)

**Comment by rishabhmwb** [comment]
this is a library all the css are already difined, its very hard  to changes its design

**Comment by Sukirti-CEDCOSS** [comment]
Verified
