### ISSUE TITLE
The option for "Enable to show time with the date on calendar" is disappeared when we are updating the product

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#106]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 3.1.3
Description -
The option for "Enable to show time with the date on calendar" is disappeared when we are updating the product

https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/7777f7c4-d005-4e5f-89d4-b930ae5a77bc

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
