### ISSUE TITLE
The time slot is not visible on either of the "Booking Unit" type

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#107]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 3.1.3
Description -
The time slot is not visible on either of the "Booking Unit" type
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/4f3c5bc3-7280-4b41-84c4-e014671eb55e)
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/b7069e88-1e64-4c11-ad87-edeea9e06e24)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/993deb23-b430-43a9-9b4d-5e35188d05ae)
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/3d09aa81-d014-4292-8a72-12b61c2f27d2)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/c197422b-b938-4bd9-a197-e68a9cc473a9)

**Comment by rishabhmwb** [comment]
time slot will be shown in only one condition and that is single calendar with hourly booking unit type
and its working at my side

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
