### ISSUE TITLE
When booking unit is selected to "day" the calendar design is not appropriate

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#108]
Woo Commerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 3.1.3
Description -
When booking unit is selected to "day"  in single type calendar, the calendar design is not appropriate
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/9e2e5fa8-ccb5-421b-8844-e85ab58ea0d8)

**Comment by navneet-cedcoss** [comment]
working fine

**Comment by ashish-wps** [comment]
user should able to select date on single calendar when Booking unit is Day(s)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/21ba91c6-e3b6-4d09-b397-74329d3244e4)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
calendar move to current date after selecting second booking day

[scrnli_19_02_2024_16-40-20.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/dff4c31d-787d-46d3-aa58-5bac70819c84)

**Comment by Ananya-Cedcoss** [comment]
unable to get the issue for now

**Comment by Ananya-Cedcoss** [comment]
The calendar is changed now this issue does not exists

**Comment by ashish-wps** [comment]
Fixed
