### ISSUE TITLE
The end time should not be less than the start time

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#109]
Woo Commerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 3.1.3
Description -
The end time should not be less than the start time. Put a validation accordingly
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/7dea8822-45d0-4d04-8690-be8675d0e059)

**Comment by prince-cedcoss** [comment]
already fixed and updated in the plugin

**Comment by ashish-wps** [comment]
Fixed
