### ISSUE TITLE
No calendar or any other purchase element after converting product into Booking type.

### ISSUE THREAD

**Issue by krzakx** [wpswings/mwb-bookings-for-woocommerce#110]
Hello, I see your product as valueable. However as in title and I do not know how even debug this.
My setup is:
WordPress: 6.3.1
Bookings For WooCommerce 3.1.3
Is there any way to debug it?

**Comment by krzakx** [comment]
OK, found an issue but totally do not underst it:
When I turned below option off, than book button has shown up! 
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/18627339/db2fecd3-0561-494e-b4b4-ee187c93ff37)

**Comment by ashish-wps** [comment]
You have misunderstood this feature, When you enable this setting booking will be shown in time period between 9:00 to 20:00 but if you disable this setting than it will be shown 24x7.
