### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#111]
Woo Commerce Version - 8.2.1
WordPress Version - 6.3.2
Plugin Version - 3.1.3
Description - phpcs issues

[PHPcs.docx](https://github.com/wpswings/mwb-bookings-for-woocommerce/files/13265969/PHPcs.docx)

**Comment by prince-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
okay
