### ISSUE TITLE
Please hide the Remove button from default time slot

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#115]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** Please hide the Remove button from default time slot

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/1b987864-a070-4e7e-920e-13788b3f9199)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
It should hide only for default time slot

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/87141645-44a5-42cc-8fac-e0e83f34cbcf)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
