### ISSUE TITLE
When user select multiple slot for booking than it's not visible on booking calendar 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#116]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** When user select multiple slot for booking than it's not visible on booking calendar 

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/729150a7-4a46-4aa4-83aa-2d6ca6236417)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/9cb38d8d-8b03-4dde-9018-5125cdb8be77)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
