### ISSUE TITLE
Content Issue in Quantity Tool tip description

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#117]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** Content Issue in Quantity Tool tip description
**Note -** Please  Recreate Tool tip description

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/19c632b4-0f90-42ee-baa4-3aadad7e5c5d)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Please remove extra S from is

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
