### ISSUE TITLE
PHP Issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#119]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** PHP issues

Deprecated: Creation of dynamic property WC_Product_Mwb_Booking::$product_type is deprecated in /home/cedcoss/Local Sites/wp1/app/public/wp-content/plugins/mwb-bookings-for-woocommerce/includes/class-wc-product-mwb-booking.php on line 24
Deprecated: Creation of dynamic property WC_Product_Mwb_Booking::$virtual is deprecated in /home/cedcoss/Local Sites/wp1/app/public/wp-content/plugins/mwb-bookings-for-woocommerce/includes/class-wc-product-mwb-booking.php on line 25

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
okay
