### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#121]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** Fatal Error
**Step to reproduce** 
1. Go to the Booking product page
2. Click on cart page or checkout page
3. Verify the result.

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/39f10259-de3e-4896-8025-9d89a6c01f9f)

[scrnli_19_02_2024_18-09-52.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/99f5a3e8-62f3-4d4e-b4cf-a8ce12cd719b)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
