### ISSUE TITLE
Booking confirmation functionality is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#122]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description -** Booking confirmation functionality is not working

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/e03f5aa8-a2ac-4a51-b74c-546ee09112a2)

**Comment by Ananya-Cedcoss** [comment]
This is used to do confirmation by admin only and whatever will be the status of the plugin that will convert into on hold and only admin will confirm
![Screenshot from 2024-02-20 19-29-31](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/79438168/e91b72d4-760b-4be9-be68-285a761e0b6b)

**Comment by ashish-wps** [comment]
Okay
