### ISSUE TITLE
Please add Prompt Popup for cancellation option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#123]
Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 3.1.6
Description - Please add Prompt Popup for cancellation option

[scrnli_23_02_2024_12-32-03.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/524a3357-b1d2-4922-babf-06e0d657ed2f)

**Comment by Ananya-Cedcoss** [comment]
fixed
