### ISSUE TITLE
Cart Total should same as product total amount

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#124]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Cart Total should same as product total amount

[scrnli_17_04_2024_16-32-02.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/f9b78007-30b0-4251-a0f1-ea39294df882)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
