### ISSUE TITLE
Time should visible in new calendar 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#125]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -**  Time should visible in new calendar 

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/5ddb8d36-236d-428e-bf6f-01d5d248748a)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/90d4a589-a456-4d35-8da2-a8608a0a79e4)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
