### ISSUE TITLE
Booking Cancel Button should visible when it will match with given status

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#126]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Booking cancel Button should visible when it will match with given status

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/3c52c853-7260-4ffa-b286-24d5fc736803)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/56de99d6-ac71-4f07-bef6-9ed1a9187400)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
