### ISSUE TITLE
Rename my booking section as Booking

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#127]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Rename my booking section as Booking

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/05ec3bd9-6198-4d02-946c-ca84a6f450b6)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
