### ISSUE TITLE
Remove time option for Day booking unit

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#128]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -**  Remove time option for Day booking unit

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/8ee42068-200c-4664-b77a-9191c360a567)

**Comment by Ananya-Cedcoss** [comment]
i have added it as check in and check out option

**Comment by ashish-wps** [comment]
Fixed
