### ISSUE TITLE
Please add validation for  availability setting

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#129]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Please add validation for  availability setting

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/b84258de-d9fb-4371-968c-2aca657a0674)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
