### ISSUE TITLE
Unnecessary Notice is showing on Checkout page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#132]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Unnecessary Notice is showing on Checkout page

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/9b304d6b-afc5-4002-bfea-ee1559f86bad)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
