### ISSUE TITLE
Decimal value should enter in Additional Costs and Additional Services

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#133]
**Woo Commerce Version - 8.7.0
WordPress Version - 6.5.2
Plugin Version - 3.1.7
Description -** Decimal value should enter in Additional Costs and Additional Services

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/b335b096-8da1-44da-a25f-1ccd8f62701d)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/4e25307f-077d-41fd-b69f-96e324b6b6de)

**Comment by Ananya-Cedcoss** [comment]
fixed
