### ISSUE TITLE
 Selected date should remove when admin click on it

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#135]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 3.1.8
Description -** Selected date should remove when admin click on it

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/eaf926e2-eab7-4934-8007-d7a060b5648d)

**Comment by Ananya-Cedcoss** [comment]
clear button is added

**Comment by ashish-wps** [comment]
Fixed
