### ISSUE TITLE
Notification should remove after clicking on OK

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#136]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 3.1.8
Description -** Notification should remove after clicking on OK

[scrnli_30_05_2024_18-11-18.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/89421c45-9210-4501-9677-e5d36aa7f9e9)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
