### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#137]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 3.1.8
Description -** Design Issue

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/ba08870a-5609-43a8-bbf9-67c46f55fe46)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
