### ISSUE TITLE
Service Cost option is disable but shown on product page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#138]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 3.1.8
Description -** Service Cost option is disable but shown on product page

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/c925a79d-1886-44fc-8814-7d3a1d0d5231)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/020e717d-84e5-403d-936b-51567cdd9937)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
