### ISSUE TITLE
Show warning on Single calendar [ Hours ]

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#140]
**Woo Commerce Version - 8.9.3
WordPress Version - 6.5.4
Plugin Version - 3.1.8
Description -** Show warning on Single calendar [ Hours ]
**Step to reproduce -** 
1. Create a Single calendar product with Hour slots.
2. Set the Up to date ( as example I selected 20-09-2024 )
3. Go to the shop page and open the product page.
4. Move the cursor on Choose Booking section.
5. Scroll on it and select any date after 20-09-2024.
6. Click on book now button
7. Verify the result.

[scrnli_13_06_2024_12-58-33.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/56f5353b-8bed-43ef-b09d-f5b124f87c7e)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/559d17c9-f370-4f9f-86ac-dc868681089f)

**Comment by Ananya-Cedcoss** [comment]
warnings are fixed
scroll is left to fix

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/09d335b2-289b-496b-9252-184de5799da8)

**Comment by Ananya-Cedcoss** [comment]
warning fixed

**Comment by ashish-wps** [comment]
[scrnli_18_06_2024_12-49-37.webm](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/dc2537d3-d734-4bcb-9f13-fb18ff5c8973)

**Comment by Ananya-Cedcoss** [comment]
not getting same issue

**Comment by ashish-wps** [comment]
Still Exist

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Done
