### ISSUE TITLE
Please add validation in Slot Hours into minutes feature

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#143]
**Woo Commerce Version - 9.0.2
WordPress Version - 6.5.5
Plugin Version - 3.1.10
Description -** Please add validation in Slot Hours into minutes feature

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/b0528005-a824-4ea1-9849-0d7e007d7d55)

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/288e9a63-46bf-4d02-870f-e881daf805ea)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
