### ISSUE TITLE
Selected booking start date appears on "booking end date" 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#144]
**Woo Commerce Version - 9.2.3
WordPress Version - 6.6.1
Plugin Version - 3.1.11
Description -** Selected booking start date appears on "booking end date" 

[scrnli_27_08_2024_12-20-03.webm](https://github.com/user-attachments/assets/ebe4846b-1f22-4a28-a5b7-ab967455350d)

**Comment by Stuti-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
