### ISSUE TITLE
Can't able to select To date on calendar 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#145]
**Woo Commerce Version - 9.2.3
WordPress Version - 6.6.1
Plugin Version - 3.1.11
Description -** Can't able to select To date on calendar 

![image](https://github.com/user-attachments/assets/3acd865c-da85-4d26-aef7-b7aefa522c77)

**Comment by Stuti-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
