### ISSUE TITLE
Displays a warning message for unavailability if a user tries to book a product for more than a week.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#146]
**Woo Commerce Version - 9.2.3
WordPress Version - 6.6.1
Plugin Version - 3.1.11
Description -** Displays a warning message for unavailability if a user tries to book a product for more than a week.

[scrnli_27_08_2024_16-16-46.webm](https://github.com/user-attachments/assets/0241f070-cf12-4bc9-a963-fa16c155424a)

**Comment by Stuti-Cedcoss** [comment]
its a client specific issue not getting replicated on my system. 
Could have occurred because the settings were not selected appropriately
