### ISSUE TITLE
Can't able to enable "Days availabilty and days availability upto Togather" setting

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#147]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 3.2.1
Description -** Can't able to enable "Days availabilty and days availability upto Togather" setting

[scrnli_q6QV4mGKYixoeM.webm](https://github.com/user-attachments/assets/b206f70a-3cdb-4eda-99f8-b6de422a2dea)

**Comment by Stuti-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
