### ISSUE TITLE
All days are disable for booking when user add upto date in single calendar 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#148]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 3.2.1
Description -** All days are disable for booking when user add upto date in single calendar 

![image](https://github.com/user-attachments/assets/5d9b5d71-b420-4bc0-8959-bc3ab9091428)

![image](https://github.com/user-attachments/assets/6cd56a97-a1c3-4db7-a9d9-3dad065f7f8e)

[scrnli_amRYiu0adsTAo6.webm](https://github.com/user-attachments/assets/f5fbef4f-9aed-44f0-bbce-ab40c2864fac)

**Comment by Stuti-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
