### ISSUE TITLE
"max booking limit per slot per hour" when user enter upto date in availability 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#149]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 3.2.1
Description -** "max booking limit per slot per hour" when user enter upto date in availability 

![image](https://github.com/user-attachments/assets/b3cba2fc-c320-44d4-a6e9-1a1f83558fd6)

**Comment by Stuti-Cedcoss** [comment]
fixed
