### ISSUE TITLE
"disable booking on that day" is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#150]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 3.2.1
Description -** "disable booking on that day" is not working
**Note -** Global  availability setting is enable

[scrnli_blCHZ8mU8t8Aua.webm](https://github.com/user-attachments/assets/44053f96-4a7d-4afe-98f1-e0ff785e1aa6)

![image](https://github.com/user-attachments/assets/e2669c43-36a1-4b87-b3e7-347da0da8176)

**Comment by Stuti-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
