### ISSUE TITLE
Two WP Swings shown

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#71]
WP - 6.0
WC - 6.6.1
Steps to reproduce -
1. Download Partial COD For WooCommerce plugin with Booking Plugin
2. Activate both plugin.
3. Go to the WordPress menu option.
4. Verify Result.
![Plugins ‹ Booking — WordPress](https://user-images.githubusercontent.com/105413021/176414438-23fbf74b-1d11-4881-b065-d5d6a7004bf8.png)

**Comment by rishabhmwb** [comment]
issue is not from this plugin
![scrnli_06_07_2022_12-27-36](https://user-images.githubusercontent.com/87125210/177488795-b5cfc4e7-e6e9-4aac-83f5-2215e9e902f1.png)
.
