### ISSUE TITLE
Home button is not available in WP Swings option.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#72]
WP - 6.0
WC - 6.6.1
Step-

1. Install Partial COD For WooCommerce plugin with Booking plugin
2. Activate the both plugins.
3. Go to the WP Swings option.
4. Verify the result.
![Bookings For WooCommerce ‹ Booking — WordPress](https://user-images.githubusercontent.com/105413021/176415529-ac39b7a3-c2db-4235-9b16-638d132c7246.png)

**Comment by rishabhmwb** [comment]
![scrnli_06_07_2022_12-27-36](https://user-images.githubusercontent.com/87125210/177488532-b50a54d6-87b9-41d7-a627-8b5726c6e656.png)
issue is not form this plugin

**Comment by rishabhmwb** [comment]
resolved

**Comment by ashish-wps** [comment]
Issue Fixed
