### ISSUE TITLE
Additional costs is not Translate

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#73]
WP - 6.0 
WC - 6.6.1
Plugin Version - 3.0.1
 Description - 
WP - 6.0
WC - 6.6.1
Plugin Version - 3.0.1
Description - 
1. Go to WP Swings option > Configuration Settings.
2. Click on Additional Services option
3. Verify the result, When Language Testing perform than Additional cost option is not translated.
![Additional Costs ‹ Booking — WordPress (1)](https://user-images.githubusercontent.com/105413021/177783557-c26d7996-5229-4f97-905c-5d952750c255.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
verified
