### ISSUE TITLE
Additional Services is not Translated

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#74]
WP - 6.0
WC - 6.6.1
Plugin Version - 3.0.1
Description - 
1. Go to WP Swings option > Configuration Settings.
2. Click on Additional Services option
3. Verify the result.
![Additional Services ‹ Booking — WordPress](https://user-images.githubusercontent.com/105413021/177784395-7f494e98-9a18-43f4-bc81-643ddf8014c2.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
verified
