### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#75]
WP - 6.0
WC - 6.6.1
Plugin Version - 3.0.1
[mwb-bookings-for-woocommerce (copy).docx](https://github.com/wpswings/mwb-bookings-for-woocommerce/files/9064098/mwb-bookings-for-woocommerce.copy.docx)

**Comment by rishabhmwb** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
[PHPcs-ORG.zip](https://github.com/wpswings/mwb-bookings-for-woocommerce/files/9220492/PHPcs-ORG.zip)

**Comment by Sukirti-CEDCOSS** [comment]
verified
