### ISSUE TITLE
services cost should not go in -ve value

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#77]
**WooCommerce Version** - 6.9.4
**Wordpress Version** - 6.0.2
**Description** - services cost should not go in -ve value
**Steps** - 
1. Download and activate the plugin.
2. Create a Booking product.
3. Create Additional Services
4. Add Booking Product to cart and decease the Additional services Quabtity.

[Luxury-Room-–-Booking.webm](https://user-images.githubusercontent.com/105413021/192952031-6085c33b-0e79-438a-bf39-cfe6e8ac1ae7.webm)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
