### ISSUE TITLE
Able to enter max in start time and min in end time.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#79]
WooCommerce Version - 7.1.0
Wordpress Version - 6.1.1
Plugin Version - 3.0.4
Description - Able to enter max in start time and min in end time.

![scrnli_30_11_2022_17-35-59](https://user-images.githubusercontent.com/105413021/204792099-3d8fe39e-c342-403d-b3a8-60f094973e2d.png)

![scrnli_30_11_2022_17-36-44](https://user-images.githubusercontent.com/105413021/204792130-facfd604-e9c5-4f2e-8b97-67c94e7610db.png)

**Comment by rishabhmwb** [comment]
issue fixed

**Comment by ashish-wps** [comment]
Fixed
