### ISSUE TITLE
Booking is not show on calendar

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#80]
**WooCommerce Version** - 7.1.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 3.0.4
**Description** - Booking is not show on calendar

https://user-images.githubusercontent.com/105413021/205288613-5d14c81e-7c2a-4241-9914-ea64f5479693.mp4

**Comment by rishabhmwb** [comment]
booking status completed means booking is over. check it without compliting status

**Comment by ashish-wps** [comment]
Fixed
