### ISSUE TITLE
The Overview image contains MWB logo

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#82]
Status - New
Woo Commerce Version - 7.3.0
WordPress Version - 6.1.1
Plugin Version - 3.0.6
Description - The Overview image contains MWB logo
  
![image](https://user-images.githubusercontent.com/85384857/217713570-eefd1e04-4db0-495b-bdd1-38f1e3279fd1.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
