### ISSUE TITLE
 The booking amount should include the "to and from" date 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#83]
Status - New
Woo Commerce Version - 7.3.0
WordPress Version - 6.1.1
Plugin Version - 3.0.6
Description - The booking amount should include the "to and from" date 
EG: booked from 14,15,16,17
The amount for 4 days should display - 2000
![image](https://user-images.githubusercontent.com/85384857/217714535-70c5481f-41cb-4328-9e2d-1f7d94c660e4.png)
![image](https://user-images.githubusercontent.com/85384857/217714555-2c1633b5-e1cc-4c29-aa6d-07f8dcbe8663.png)

**Comment by rishabhmwb** [comment]
this is the work flow of the plugin we do not include to date in cost in case of unit set on days

**Comment by Sukirti-CEDCOSS** [comment]
verified
