### ISSUE TITLE
Restrict the user per booking or put a note that the restriction is only one user one booking

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#84]
Status - New
Woo Commerce Version - 7.3.0
WordPress Version - 6.1.1
Plugin Version - 3.0.6
Description -  Restrict the user per booking or put a note that the restriction is only one user one booking
![image](https://user-images.githubusercontent.com/85384857/217744626-1c7bb440-a0b3-4633-935c-7f89a0f54751.png)

![image](https://user-images.githubusercontent.com/85384857/217744515-3ed2cdd4-3f50-4c8c-884c-0caca34feef0.png)

**Comment by rishabhmwb** [comment]
![Cart – bookings](https://user-images.githubusercontent.com/87125210/218392840-6b5f7d2b-a637-4f65-9bd3-0c95d25789fd.png)
it will work but timing should be same , if we select different timing then it will count its a diffrent booking if timing is not same

**Comment by Sukirti-CEDCOSS** [comment]
verified
