### ISSUE TITLE
The user should be able to book more than one time slot or time slots for multiple date

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#88]
Status - New
Woo Commerce Version - 7.8.0
WordPress Version - 6.2.2
Plugin Version - 3.1.0
Description:
The user should be able to book more than one time slot or time slots for multiple date
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/a43cb95e-71e9-4a07-8804-59b22c9613ea)

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/2a6dd2d0-4ae1-4c33-a948-99f439084ca7)

**Comment by Ananya-Cedcoss** [comment]
for need to research so it will be fix in next update

**Comment by Ananya-Cedcoss** [comment]
this feature is not given by calendar

**Comment by ashish-wps** [comment]
As per developer that's not an issue
