### ISSUE TITLE
The date and time on the text area should be displayed completely 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#89]
Status - New
Woo Commerce Version - 7.8.0
WordPress Version - 6.2.2
Plugin Version - 3.1.0
Description:
The date and time on the text area should be displayed completely to avoid confusion
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/c4e75fd2-9cb7-47bb-9756-64ec986a71f8)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
