### ISSUE TITLE
The date that is enabled for the upcoming holiday shows are available on the product booking

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#90]
Status - New
Woo Commerce Version - 7.8.0
WordPress Version - 6.2.2
Plugin Version - 3.1.0
Description:
The date that is enabled for the upcoming holiday shows are available on the product booking
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/916f2054-20d8-42e0-a45e-cdb0d4c551f9)
![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/85384857/3fe0b19b-e4fc-42e8-89be-32d5326ee5f6)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
