### ISSUE TITLE
PHPcs Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/mwb-bookings-for-woocommerce#92]
File
[PHPcs.xml.zip](https://github.com/wpswings/mwb-bookings-for-woocommerce/files/11795631/PHPcs.xml.zip)
[mwb-bookings-for-woocommerce.zip](https://github.com/wpswings/mwb-bookings-for-woocommerce/files/11795632/mwb-bookings-for-woocommerce.zip)

**Comment by rishabhmwb** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
