### ISSUE TITLE
Calendar did not work properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#94]
**Woo Commerce Version** - 7.8.2
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.1
**Description** : Calendar did not work properly

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/a1340f87-3406-4615-9541-1e46e3393a8c)

https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/0e58114b-0ab5-4573-8a1e-af807fbd3fc7

**Comment by rishabhmwb** [comment]
https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/87125210/440bd648-1fda-4479-a0c0-1e9ad2ae6f08



in web version its already working , issue was in mobile version and i fixed that

**Comment by ashish-wps** [comment]
"Set days availability " is working properly


![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/dca628ee-544a-4bcd-a451-4591b6c99520)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
