### ISSUE TITLE
Max / Min converter  and notification is not visible when user enter more value than limit in people option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#96]
Woo Commerce Version - 7.8.2
WordPress Version - 6.2.2
Plugin Version - 3.1.1
Description : Max / Min converter  and notification is not visible when user enter more value than limit in people option

https://drive.google.com/drive/folders/1eGQ1ZRCuAwzEJZDXsygshcVHF7sw3lhF?usp=drive_link

**Comment by rishabhmwb** [comment]
https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/87125210/f0158fbe-dc48-4336-9475-e3b8311e9027

no such issue found

**Comment by ashish-wps** [comment]
okay
