### ISSUE TITLE
In negative value Additional Cost / services created but value is not available

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#97]
**Woo Commerce Version** - 7.8.2
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.1
**Description** : In negative value Additional Cost / services created but value is not available

https://drive.google.com/drive/folders/1wARZN4EIKV_ART77ZzzSnG7W2qsIe9uj?usp=drive_link

**Comment by rishabhmwb** [comment]
not the issue , its a functionality

**Comment by ashish-wps** [comment]
okay
