### ISSUE TITLE
Upcoming Holiday calendar available in Single calendar { Booking type }

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/mwb-bookings-for-woocommerce#98]
**Woo Commerce Version** - 7.9.0
**WordPress Version** - 6.2.2
**Plugin Version** - 3.1.2
**Description** - Upcoming Holiday calendar available in Single calendar { Booking type }

![image](https://github.com/wpswings/mwb-bookings-for-woocommerce/assets/105413021/0a0db0bc-28e1-47d7-90d8-a40ef74baea5)

**Comment by rishabhmwb** [comment]
fixed

**Comment by rishabhmwb** [comment]
fixed
